language: python

python:
  - "2.7"
  #- "3.4"
  - "3.5"
  - "3.6"

install:
  - export BUILD_DIR=`pwd -P`
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true

  - conda create -n earth-env -c ioam -c conda-forge -c scitools/label/dev -c gbrener earth-env
  - source activate earth-env
  - export ELM_EXAMPLE_DATA_PATH=$(pwd -P)/elm-data
  - mkdir -p $ELM_EXAMPLE_DATA_PATH && cd $ELM_EXAMPLE_DATA_PATH && python "${BUILD_DIR}/scripts/download_test_data.py"
  - cd $BUILD_DIR
  - ls -lRth $ELM_EXAMPLE_DATA_PATH
  - python setup.py develop

script:
  - cd $BUILD_DIR
  - DASK_SCHEDULER=SERIAL py.test -m 'not slow' -v
