language: python

python:
  - "3.5"

env:
  - EARTH_VERS=2.7
  - EARTH_VERS=3.5
  - EARTH_VERS=3.6

install:
  - MAKE_MINICONDA=1 . build_earthio_env.sh

script:
  - cd $BUILD_DIR
  - py.test -m 'not slow' -v earthio/tests
