language: python

python:
  - "3.5"

env:
  - PYTHON_TEST_VERSION=2.7
  - PYTHON_TEST_VERSION=3.5
  - PYTHON_TEST_VERSION=3.6

install:
  - export EARTHIO_TEST_ENV=earth-env-test
  - MAKE_MINICONDA=1 . build_earthio_env.sh

script:
  - cd $BUILD_DIR
  - py.test -m 'not slow and not requires_elm' -v earthio/tests
