language: python

python:
  - "3.5"

env:
  - EARTH_VERS=2.7
  - EARTH_VERS=3.5
  - EARTH_VERS=3.6

install:
  - export BUILD_DIR=`pwd -P`
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes true
  - conda env update -n earth-env -f environment.yml
  - source activate earth-env
  - python setup.py develop

  - export ELM_EXAMPLE_DATA_PATH=$(pwd -P)/elm-data
  - conda install -c defaults -c conda-forge requests pbzip2 python-magic six # for download_test_data.py
  - mkdir -p $ELM_EXAMPLE_DATA_PATH && cd $ELM_EXAMPLE_DATA_PATH && python "${BUILD_DIR}/scripts/download_test_data.py"
  - cd $BUILD_DIR
  - ls -lRth $ELM_EXAMPLE_DATA_PATH

script:
  - cd $BUILD_DIR
  - DASK_SCHEDULER=SERIAL py.test -m 'not slow' -v earthio/tests
