name: earth-env
channels:
  - gbrener
  - ioam
  - conda-forge
  - scitools/label/dev
dependencies:
  - attrs
  - bokeh
  - cartopy
  - colorcet
  - dask
  - datashader
  - dill
  - distributed
  - geoviews
  - holoviews
  - iris
  - jupyter
  - krb5
  - matplotlib
  - networkx
  - numba
  - numpy
  - pandas
  - paramnb
  - pbzip2  # elm-data
  - pyproj
  - pytables
  - pytest
  - python=3.5
  - python-magic  # elm-data
  - rasterio
  - requests
  - scikit-learn
  - scipy
  - shapely
  - statsmodels
  - tblib
  - xarray
  - xarray_filters
  - yaml
  - six
  - pip:
      - cachey
