name: earth-env

channels:
  - ioam
  - conda-forge
  - scitools/label/dev
  - elm

dependencies:
  - deap
  - dill
  - gdal
  - iris
  - pytables
  - python-magic
  - rasterio
  - scikit-image
  - scikit-learn
  - statsmodels
  - colorcet
  - datashader
  - geoviews
  - paramnb
  - jupyter
  - elm # only for unit-testing
  - pip:
    - cachey
