name: earth-env
channels:
  - gbrener
  - ioam
  - conda-forge
  - scitools/label/dev
dependencies:
  - deap
  - dill
  - gdal =2.1.*
  - iris
  - pytables
  - pytest
  - python-magic
  - rasterio
  - scikit-image
  - scikit-learn
  - statsmodels
  - colorcet
  - datashader
  - geoviews
  - paramnb
  - jupyter
  - pip:
    - cachey
