name: earth-env
channels:
  - ioam
  - conda-forge
  - scitools/label/dev
  - elm
  - elm/label/dev

dependencies:
  - conda-forge::bokeh
  - anaconda::cartopy
  - colorcet
  - dask
  - datashader
  - dill
  - distributed
  - conda-forge::geoviews
  - conda-forge::holoviews
  - iris
  - jupyter
  - krb5
  - matplotlib
  - networkx
  - numba
  - numpy
  - pandas
  - pbzip2  # elm-data
  - conda-forge::pydap
  - conda-forge::pynio
  - pyproj
  - pytables
  - pytest
  - python=2.7
  - python-magic  # elm-data
  - anaconda::rasterio
  - requests
  - scikit-learn
  - scipy
  - shapely
  - statsmodels
  - tblib
  - xarray
  - xarray_filters
  - yaml
  - six
  - gdal=2.1.*
  - pip:
      - cachey
      - git+https://github.com/ContinuumIO/xarray_filters.git # for testing
