package:
  name: earthio
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'notag') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}

requirements:
  build:
    - python
    - setuptools

  run:
    - deap
    - dill
    - gdal
    - iris
    - pytables
    - python-magic
    - rasterio
    - scikit-image
    - scikit-learn
    - statsmodels
    - colorcet
    - datashader
    - geoviews
    - paramnb
    - jupyter

about:
  home: http://github.com/ContinuumIO/elm
  license: MIT

extra:
  channels:
    - defaults
    - gbrener
    - ioam
    - conda-forge
    - scitools/label/dev
    - elm

  maintainers:
    - Peter Steinberg - Continuum Analytics - psteinberg [at] continuum [dot] io
    - Greg Brener - Continuum Analytics - gbrener [at] continuum [dot] io

test:
  imports:
    - earthio

  requires:
    - pytest
    - elm # Only needed for tests
