package:
  name: earthio
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'notag') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}

requirements:
  build:
    - python
    - setuptools

  run:
    - bokeh
    - cartopy
    - colorcet
    - dask
    - datashader
    - dill
    - distributed
    - geoviews
    - holoviews
    - iris
    - jupyter
    - krb5
    - matplotlib
    - networkx
    - numba
    - numpy
    - pandas
    - paramnb
    - pyproj
    - pytables
    - python
    - python-magic
    - rasterio
    - requests
    - scipy
    - shapely
    - statsmodels
    - tblib
    - xarray
    - xarray_filters
    - yaml
    - six

about:
  home: http://github.com/ContinuumIO/elm
  license: MIT

extra:
  channels:
    - defaults
    - gbrener
    - ioam
    - conda-forge
    - scitools/label/dev

  maintainers:
    - Peter Steinberg - Continuum Analytics - psteinberg [at] continuum [dot] io
    - Greg Brener - Continuum Analytics - gbrener [at] continuum [dot] io

test:
  imports:
    - earthio

  requires:
    - pytest
    - xarray_filters
